### ISSUE TITLE
Github actions - easy config can't see .env.test

### ISSUE THREAD

**Issue by rostgoat** [rubiin/nestjs-easyconfig#289]
When I run my tests locally, I have a `.env.dev` and `.env.test` files in my root dir. When I push to github, I don't push those files. Instead, I specify my `env` in my workflow. However, since github actions runs `npm run test` which sets the `NODE_ENV` to `test`, easyconfig tried to look for `.env.test` file (which is not pushed up) and throws error.

What's the way around this?

Error:

```
Error: ENOENT: no such file or directory, open '/home/runner/work/api/.env.test'
```
My EasyconfigModule lives in a module called `database.module` like so:

```
@Module({
  imports: [
    EasyconfigModule.register({}),
    TypeOrmModule.forRootAsync({
      useClass: DatabaseService,
    }),
  ],
  providers: [DatabaseService],
})
export class DatabaseModule {}
```

this is database.service
```
const prod = process.env.NODE_ENV === 'production'
const test = process.env.NODE_ENV === 'test'
@Injectable()
export class DatabaseService implements TypeOrmOptionsFactory {
  createTypeOrmOptions(): TypeOrmModuleOptions {
    return {
      type: 'postgres',
      host: process.env.DATABASE_HOST,
      port: Number(process.env.DATABASE_PORT),
      username: process.env.DATABASE_USER,
      password: process.env.DATABASE_PASSWORD,
      database: process.env.DATABASE_NAME,
      synchronize: prod ? false : true,
      dropSchema: false,
      logging: prod || test ? false : true,
      entities: [__dirname + '/../**/**.entity{.ts,.js}'],
      migrations: [`${__dirname}/migrations/**/*{.ts,.js}`],
      cli: {
        migrationsDir: 'src/migrations',
      },
    }
  }
}
```

workflow yml

```
name: API Integration Tests

on:
  pull_request:
  push:
    branches: -master

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x]

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: mydb
          POSTGRES_PASSWORD: root
          POSTGRES_USER: postgres
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
        env:
          DATABASE_HOST: localhost
          DATABASE_PORT: 5433
          DATABASE_USER: postgres
          DATABASE_PASSWORD: root
          DATABASE_NAME: cars
          NODE_ENV: test
      - run: npm run test
```
